[n1]
lemma = " | "
note = "Digtet indledes og afsluttes, symmetrisk, med en adskilt gruppe på 4 vers. De første fire vers skal svare til »udskriften« på et rigtigt brev. En sådan udskrift bestod normalt kun af en adressat-angivelse, men dén (_accipe, mi Titan_) er her udvidet til en sentens der beskriver brevets grundlæggende situation, på samme måde som Ovid i heroiderne udvider den romerske brevindledningsformular. Digtet får herved to sådanne adressat-angivelser (en »moderne« og en »romersk«) eftersom det første distikon i selve heroiden (v. 5-6) imiterer de tilsvarende distika hos Ovid. På lignende måde svarer de sidste fire vers (v. 605-8) til et rigtigt brevs angivelse af sted og dato. "

[n]
lemma = "En tibi sexcentos ... versus | "
note = "Selve Heroiden, fraregnet de to grupper på hver 4 vers der udgør henholdsvis udskrift og efterskrift, er på præcis 600 vers. At dette nævnes i digtets første vers implicerer formodentlig at det har symbolsk betydning.
Ifølge det 16. århundredes kendteste magiske værk, Agrippa von Nettesheims _De Occulta Philosophia_, skal alle tal over 10, hvad symbolik angår, opfattes som multiplicata af lavere tal (Agrippa Lib. II cap. XV). Det er derfor naturligt at se tallet 600 som 6 x 100 (100 = 10 x 10) (således også Meyer 1945, 189). 6 er ifølge Agrippa det fuldkomne eller fuldkommelsens tal (numerus perfectionis, Agrippa II.IX): Verden blev skabt på seks dage, mennesket på den sjette. Samtidig er det frelsens tal, eftersom Kristus døde på den sjette dag. 10, rækkens sidste tal, er det komplette tal (... _hic dicitur omnis numerus siue uniuersus atque numerus completus._ II.XIII) og symboliserer det gennemførte livsløb osv. 100 (10 x 10) er »den fuldendte perfektion« og 1000 »den absolutte perfektion« (II.XV).
Man kan gætte på at tallet kan forstås alkymistisk om fuldbyrdelsen af »det store værk«. Dets gennemførelse skulle svare til skabelsen også hvad antallet af dage angår (Martinus Rulandus, _Lexicon Alchemiæ sive Dictionarium Alchemisticum_, Francofurti 1612). I så fald hentydes der her til den identifikation af digtets mål, Titans hjemkomst, med fuldførelsen af den alkymistiske proces som udvikles i digtets alkymistiske afsnit (ca. v. 105 ff, jvf. også v. 606 m. komm.). Det må dog understreges at der ikke er konkret belæg for en sådan tolkning af tallet.
Samtidig er der vel tale om et spil på den klassiske latinske brug af tallet 600 som indbegrebet af et stort antal, omtrent som vi bruger 117. Sætningen kan forstås som en ren spøg: _Sexcentos_ er brugt i betydningen »en hel masse«, men digtet har faktisk præcis 600 vers. "

[n]
lemma = "mi Titan | "
note = "Ved at Erik Lange kaldes Titan, dvs. Solen, angives hans tilknytning til alkymien. Denne er ifølge _Tabula Smaragdina_ »Solens værk« (Tab. Smar. 13: _Completum est quod dixi de operatione solis_). Dette skyldes både at Solen i det almindelige analogisystem kemisk svarer til guld, og dens naturlige tilknytning til ilden.
Peder Hansen Resen (_Inscriptiones Haffnienses_, 1668, s. 410) foreslår to andre forklaringer på dette tilnavn. For det første hans ungdom, skønhed og elegante opførsel, og for det andet at solen ved hans fødsel var ved at stå op (_in orientis cardine ... versaretur_) – en position hvor den ofte af digterne kaldes Titan. Begge forslag er sandsynligvis gætteri fra Resens side. Det første er for banalt til at være tilstrækkelig forklaring. At Titan faktisk var født ved solopgang fremgår af hans horoskop senere i digtet (v. 255). Den særlige konnotation ved navnet er til gengæld ikke noget anerkendt faktum. Ordet Titan bruges ganske vist ikke sjældent om den opgående sol, men alligevel ikke oftere end at det kan forklares med solopgangsscenernes generelle hyppighed i romersk poesi. "

[n]
lemma = "sunt ideo multi | "
note = "_tam multi_ havde været mere naturligt – og det havde V også oprindelig (_Tam prolixa ideo est_ ...). Den nuværende læsemåde er en konsekvensrettelse af T efter en rettelse i v. 1: Hvor der oprindelig refereredes til ordet _epistola_ i v. 1 skal der nu refereres til _versus_. "

[n]
lemma = " | "
note = "Tankegangen i dette vers gentages i de to næste, som udgør ind-ledningen til den ovidianske heroide. Temaet fra heroidens indledning (som er en imitation af de tilsvarende vers i Ov. Her. 1.1-2) »genbruges« altså her i brevets udskrift (men denne gang uden sproglige imitationer). "

[n]
lemma = " | "
note = "En række af Ovids heroider har som indledning et distikon som dette, der kan opfattes som variationer over de romerske prosabreves »præscripter« (_Marcus Quinto salutem dicit_, »M. hilser Q.«). Disse distika indeholder hos Ovid (både i _Heroides_, _Epistolae ex Ponto_ og _Tristia_) og i et eksempel hos Properts (4.3) normalt navn på afsender og modtager knyttet sammen v.h.a. et udtryk der i større eller mindre grad (men altid i nye variationer) ligner _salutem dicere_. Dette udtryk er normalt samtidig udvidet til en slags sentens (ofte et ordspil), der anskueliggør digtets situation. Et meget typisk, helt ovidiansk, eksempel på dette er be¬gyndelsen af Tycho Brahes digt til Erik Lange fra 1584 (XV.3.27-8, jvf. Peter Zeeberg »Amor på Hven: Tycho Brahes digt til Erik Lange.« _Renæssancen: Dansk, Euro¬pæisk, Globalt_, udg. af Minna Skafte Jensen og Marianne Pade, 161-81):

Hanc tibi Tycho tuus transmittit Erice salutem,
  Si qveat ulla salus esse, ubi regnat amor.

Erik, Din gode ven Tycho sender dig dette »lev vel«
– hvis ellers den kan leve vel der er i kærlighedens vold.

Disse distika i Ovids _Heroides_ er grundigt undersøgt af Ernst-Alfred Kirfel (_Unterzuchungen zur Brief¬form der Heroides Ovids_. (Noctes Romanae 11). Bern/Stuttgart 1969, 1-36). Ægtheden af en lang række af dem har været stærkt diskuteret i de sidste 100 år (se Kirfel 1969, 37 ff), men på Tycho Brahes tid ansås de for et genrekrav. V. 5-6 imiterer det indledende distikon i Ov. Her. 1 – v. 5 kun indholdsmæssigt, v. 6 også sprogligt. I V's oprin¬delige ordlyd havde dog også v. 5 sproglige overens¬stemmelser med Ovid:

(Ovid) Hanc tua Penelope lento tibi mittit, Ulixe
(V) Haec tua ab Urania tibi fertur epistola Titan

T's rettelse er dog ganske i Ovids stil, jvf. fx Ov. Her. 3.1:

(Ovid) Quam legis, a rapta Briseide littera venit
(T) Venit ab Urania, quam cernis epistola, Titan"

[n]
lemma = "Urania"
note = "Urania er astronomiens muse, og bruges i flere af Tycho Brahes digte som personifikation af hans videnskab. Både i »Uraniaelegien« (i _De Nova Stella_, 1573) og i digtet til Niels Kaas lader han hende åbenbare sig for ham og kalde ham til arbejdet i hendes, altså astronomiens, tjeneste. I digtet til Jacob Ulfeldt, foretager han i typisk renæssancestil en »museoverførelse«, hvor Urania, der ikke længere har hjemme noget sted, overføres til Norden (se videre: Peter Zeeberg, _Den praktiske muse. Tycho Brahes brug af latindigtningen._ (Studier fra Sprog- og Oldtidsforskning 321). København 1993).
Her, som i det omtalte interne sprog på Hven, bruges navnet om Sophie Brahe, på grund af hendes store interesse for astrologi. Navnet findes også andre steder i Tycho Brahes korrespon¬dance.
 "

[n]
lemma = "Nil sibi rescribi, te sed adesse cupit | "
note = "jvf. Ov. Her. 1.2: _Nil mihi rescribas, sed tamen ipse veni._
Præcis samme tanke, men set fra den anden side findes i det ene af de to epigrammer Tycho Brahe har skrevet om Sophie og Erik Lange:

Hanc tuus Ericus tibi, chara Sophia, salutem
  Mittit, et o semet mittere posse datum. "

[n]
lemma = "perarata | "
note = "»gennempløjet« dvs. »(be)skrevet« – et typisk ovidiansk udtryk (om breve: Met. 9.564, Am. 1.11.7, AA. 1.455 og 3.485, Tr. 3.7.1). Udtrykket skyldes at man i oldtiden ridsede bogstaverne i vokstavler, så billedet har mistet sin betydning her. "

[n]
lemma = "charta"
note = "i betydningen »brev« almindeligt hos Ovid."

[n]
lemma = "nostris ars invida votis | "
note = "parallel til v. 22, ... _ut votis ars sit amica tuis_ (se komm. til v. 21).
Teksten i v. 9 er en rettelse af T, V havde oprindelig: _Detinet Ars nimium nostris inimica lacertis_ (»Kunsten, der er alt for uvenlig over for mine arme, holder på dig«). Som det ses, manglede derved parallellen _votis/votis_ – til gengæld fandtes en anden: _inimica/amica_. Den oprindelige version imiterede Ov. Her. 1.47: _Sed mihi quid prodest vestris disiecta lacertis / Ilios_ ... "

[n]
lemma = "invida | "
note = "om ting og begreber, som her, specielt almindeligt hos Ovid (fx Met. 9.486: _nox ... coeptis invida nostris_). "

[n]
lemma = "Nec tanti Hermes, nec tota chimia foret | "
note = "Jvf. Ov. Her. 1.4: _Vix Priamus tanti totaque Troja fuit._ "

[n]
lemma = "Chimia | "
note = "Skanderes her ∪–∪. Håndskriftets oprindelige tekst havde –∪∪, hvilket svarer til v. 374. _Chimica_ skanderes derimod konsekvent –∪∪ i v. 373 og v. 380. "

[n]
lemma = "Hermes | "
note = "Hermes Trismegistos, den angivelige forfatter til bl.a. _Tabula Smaragdina_. Se videre under v. 166 ff."

[n]
lemma = "foret | "
note = "Er vel et ønske. Et sådant udtryk, uden _utinam_, er i klassisk latin ret sjældent. Her er det nødvendigt af hensyn til Ovid-parallellen. "

[n]
lemma = "ars vana | "
note = "Det fastslås fra begyndelsen at alkymien er en »tom«, dvs. frugtesløs eller formålsløs, videnskab (se videre i komm. til v. 374: _Chimia falsa nimis_). Derpå vendes begrebet til alkymiens virkning: Den giver tomme punge og tomme senge (v. 12)."

[n]
lemma = "vacuo linquor ... thoro | "
note = "Jvf. Ov. Her. 1.7: _non ego deserto jacuissem frigida lecto._ "

[n]
lemma = "sine sole dies, sine sidere noctes / Orba traho | "
note = "Ovid-imitationen fortsæt¬ter: Ov. Her. 1.8-9: non quererer tardos ire relicta dies / nec mihi quaerenti spatiosam fallere noctem / ... Et parallelt udtryk om Titan forekommer i v. 21-22, se komm. ad loc. "

[n]
lemma = "sine sidere | "
note = "_Sidus_ kan bruges om et enkelt himmellegeme, og kunne derfor her være månen, men eftersom det står parallelt med _sine sole_, er det mere sandsynligt at det her betyder »stjerner«, generelt. "

[n]
lemma = "Solque Jubarque | "
note = "Fordi Titan er Solen. "

[n]
lemma = "Averni | "
note = "Underverdenen. Avernersøen i Syditalien var efter sagnet nedgangen til underverdenen.
Med underverdensbilledet spilles der, ud over det sorte og mørke, på alkymiens tilknytning til jorden – som det fx udtrykkes i v. 369 ff. (Jvf. udtrykket _Stygias ... lymphas_ i v. 35).
 "

[n]
lemma = "nitidos | "
note = "Både »skinnende«, om Solen (dagen), og »ren«, »hvid«, i modsæt¬ning til _atra._ "

[n]
lemma = "atra | "
note = "Må vel her også være et spil på begrebet »den sorte kunst« om den skadelige magi i modsætning til den hvide, tilladte. Altså endnu en antydning af alkymiens videnskabe¬lige mindreværd. "

[n]
lemma = "fit carbonibus atris | "
note = "Alkymistiske eksperimenter gik normalt ud på at nedbryde forskellige stoffer ved opvarmning over kul."

[n]
lemma = "Non decuit niveas res ita nigra manus | "
note = "jvf. Ov. Her. 1.10: _lassaret viduas pendula tela manus._ – Der er ikke indholdsmæssigt nogen særlig for¬bindelse mellem Tycho Brahes og Ovids vers, men _niveas ... manus_ står samme sted i pentametret som _viduas ... manus_ og syntax og ordstilling er nøje parallelli-seret. I begge digte begynder i næste vers et afsnit om de farer manden er udsat for."

[n]
lemma = "niveas ... manus | "
note = "Denne modstilling af elskerens hvide, fine (_tenella ... pectora_, v. 28), smukke (_bella labella_, v. 32), bløde (_cutis ... mollior ... nive_, v. 33-4) legeme og det grove arbejde genfindes i Properts 4.3 – et brevdigt der er meget i slægt med Ovids heroider. Arethusa skriver til sin mand, Lycotas, der er i krig, og arbejdet er altså her soldatens:

dic mihi, num teneros urit lorica lacertos?
  num gravis imbellis atterit hasta manus? (Prop. 4.3.23-4)

Tankegangen uddybes i _Urania Titani_ i v. 27-34."

[n]
lemma = " | "
note = "Efter »jeg er forladt« kommer som i Ov. Her. 1 »du er i fare«. Men hvor Penelope forestiller sig større farer end virkelighedens (_graviora pericula veris_, v. 11), har Tycho Brahe først en opremsning af alkymiens virkelige farer, og først derefter den overdrevne frygt (v. 43: _majora pericula veris_)."

[n]
lemma = "curis nimiis noctesque diesque / carperis | "
note = "Jvf. v. 13-4: Ligesom Urania lider dag og nat, fordi videnskaben er uvenlig over for hendes ønsker (_ars invida votis_, v. 9), lider Titan nat og dag for at videnskaben skal opfylde hans ønsker (_ut votis ars sit amica_, v. 22) – kiastisk opstillet. Herved parallelli¬seres Titans søgen efter guld med Uranias venten på Titan. "

[n]
lemma = " | "
note = "Så snart analogien mellem alkymien og Uranias venten er blevet antydet, gøres der opmærksom på alkymiens håbløshed! "

[n]
lemma = "quod et usque requiris | "
note = "Formodentlig _quod_ i betydningen »skønt«: »skønt du søger til stadighed«. "

[n]
lemma = "animus ... cecidisse dolet | "
note = "_Animus cadit_: »Modet synker«, »modet tabes«. Sætningen må vel opfattes som _animus dolet se cecidisse_, dvs: »Smerter det ikke dit sind at tabe modet over så store forhåbninger« (for konstruk-tionen jvf. Hor. Carm. 4.4.62: _Vinci dolentem ... Herculem_). Men kombi¬nationen af den sjældne konstruk¬tion og ordspillet _animus dolet_ / _animum cecidisse_ er anstrengt. "

[n]
lemma = "anhela | "
note = "»Stakåndede«. "

[n]
lemma = "spiracula | "
note = "»Lufthuller«. Her formodentlig næsebor eller bronchier (?) (Apuleius, Pl. I.16, har _pulmonum spiracula_). "

[n]
lemma = "materies | "
note = "Betyder formodentlig ligesom _materia_ i det selvbiografiske afsnit af Tycho Brahes _Mechanica_ »materialet«, dvs. de stoffer alkymisten eksperimenterer med. Jvf. v. 159. "

[n]
lemma = " | "
note = "	En sproglig omvending af typisk ovidiansk art. (Jvf. fx Ov. Am. 1.7.41, hvor pigen er blevet slået så hun har fået blå mærker: _Aptius impressis fuerat livere labellis_ – det burde være sugemærker!). "

[n]
lemma = "ipsa sat omnia novi | "
note = "Sophie beskæftigede sig selv med kemi. "

[n]
lemma = "species | "
note = "Arter af _materies_? "

[n]
lemma = "Sæpe cutis toto maculis tibi corpore liuet | "
note = "T's rettelse i teksten er velanbragt. Den oprindelige tekst, _Sæpe cutis maculas toto tibi corpore spargit_ kan næppe kan siges at give mening. "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "

[n]
lemma = " | "
note = " "