[n1]
lemma = "LEGATI GALLI | den franske gesandt"
note = "Charles Dançay, født ca. 1509, var fra 1548 og indtil sin død i 1589 fransk gesandt i København. Han var en nær ven af Tycho Brahe og lagde i 1576 grundstenen til Uraniborgs fundamenter. Bio- og bibliografi i Ehrencron-Müller, Forfatterlexicon (1924-39)."

[n2]
lemma = "Mathesis"
note = "Det græske ord _mathesis_ betyder grundlæggende ‘læreproces’ eller ‘lærdom’. På Tycho Brahes tid bruges det også som samlebetegnelse for det, vi ville kalde de eksakte videnskaber." 

[n3]
lemma = "omnes Geometriæ ignaros a sua schola ... arcebat | nægtede alle uden kendskab til geometri adgang til sin skole"
note = "En sen (og fejlagtig) tradition ville vide, at der over indgangen til Platons Akademi i Athen stod: ‘Ingen har adgang uden kendskab til geometri.’" 

[n4]
lemma = "Grammaticæ et linguarum studijs | grammatiske ogsproglige studier"
note = "Tycho hentyder her til det faktum at al akademisk virksomhed på dette tidspunkt foregik på latin, og al faglitteratur var på latin (eller græsk), hvorfor al skole- og den en vis grad også universitetsundervisning fokuserede på indlæring af de klassiske sprog. " 

[n5]
lemma = "Vitellio | Vitellio"
note = "Erazmus Ciołek Witelo (ca. 1230 – efter 1280, før 1314), polsk munk og naturforsker, forfatter til et værk om optik (_Optica_ el. _Peri optikes_), der blev trykt første gang 1535 under titlen _Perspectiva _og senere medtaget Friedrich Risners _Opticae thesaurus_, 1572." 

[n6]
lemma = "Alhazen Arabs | araberen Alhazen"
note = "Abu Ali al-Hasan ibn al-Haitham (lat. Alhacen, Avennathan eller Avenetan, ca. 965 - ca. 1040, altså før Witelo), arabisk matematiker, optiker og astronom. Hans værk om optik blev i 12. årh. oversat til latin (_De aspectibus eller Perspectiva_). Værket blev trykt sammen med Witelos _Optica_ i Friedrich Risners _Opticae thesaurus_, 1572." 

[n7]
lemma = "Josephus ... asseverat | Josephus ... fastslår"
note = "Josephus: _De jødiske Antikviteter_ 1.8.2." 

[n8]
lemma = "multiformemque | mangeformede"
note = "Tycho hentyder til Månens faser." 

[n9]
lemma = "Ex huius Adami liberis Seth educatus ... | Seth, en af denne Adams børn, ..."
note = "Josephus: _De jødiske Antikviteter_ 1.2.3." 

[n10]
lemma = "Abrahamum Patriarcham ... | At patriarken Abraham ..."
note = "Josephus: _De jødiske Antikviteter_ 1.7.1." 

[n11]
lemma = "de Abrahamo narrat | fortæller noget tilsvarende om Abraham"
note = "Filon fra Alexandria: _Om Abraham_ 18.32." 

[n12]
lemma = "Josephus non obscure innuit | Josefus tydeligt fremhæver"
note = "Josephus: _De jødiske Antikviteter_ 1.4." 

[n13]
lemma = "Ptolomæo | Ptolemæus"
note = "Klaudios Ptolemaios, Claudius Ptolemæus (ca. 100-ca. 170), græsk astronom, matematiker og geograf fra Alexandria i Egypten, hvis hovedværk, Almagest, blev grundlaget for den astronomiske videnskab de følgende ca. 1400 år." 

[n14]
lemma = "Timochares | Timochares"
note = "Timocharis von Alexandria (ca. 320-260 f.Kr.), græsk astronom." 

[n15]
lemma = "Hyparchus Rhodius | Hipparchus fra Rhodus"
note = "Hipparchos (ca. 190-ca. 125 f.Kr.), græsk astronom, der anses for den videnskabelige astronomis grundlægger. Han blev født i Nikæa og tilbragte formentlig det meste af sit liv på Rhodos." 

[n16]
lemma = "Dum conuexa Poli ... laudesque manebunt | Lige så længe som Titan vil stråle ... hans hæder "
note = "De tre heksametre er Tychos eget værk; Titan er Solen, Cynthia Månen (egl. et tilnavn til Artemis/Diana efter et lille bjerg på øen Delos, hvor hun og Apollon blev født)." 

[n17]
lemma = "Albategnius | Albategnius"
note = "Latinsk navn for den arabiske astronom al-Battani (Abu Abdullah Muhammad ibn Jabir al-Battani, 858-929), hvis værker blev oversat til latin i 1100-tallet og meget brugt i Europa, heriblandt hovedværket _De motustellarum_ (Om stjerners bevægelser) med tabeller og et fiksstjernekatalog nød stor udbredelse i Europa i middelalderen." 

[n18]
lemma = "Rex Arragoniæ Alphonsus | Alfonsus af Aragonien"
note = "Alfonso 10. den Vise (1221-1284), konge af Castilien fra 1252; Under Alfonsos personlige overvågning udarbejdede et team af astronomer de såkaldte Alfonsinske Tavler, et astronomisk tabelværk til beregning af Solens, Månens og planeternes placering på himlen." 

[n19]
lemma = "Nicolaus Copernicus | Nicolaus Copernicus"
note = "Nikolaus Kopernikus (1473-1543), polsk astronom, der i sit hovedværk _De revolutionibus orbium coelestium_ (Om himmelsfærernes kredsbevægelser) argumenterede for det heliocentriske verdensbillede." 

[n20]
lemma = "Lucidus apparet Titan ... uiete geruntur | strålende fremtræder Titan ... evindelig lykke og velfærd. "
note = "Tychos egne vers. Titan er Solen" 

[n21]
lemma = "hæc inferiora et caduca | det nedre og forgængelige,"
note = "Dvs. den sublunare fysiske verden." 

[n22]
lemma = "Os sublime dedit, ... ad sidera tollere vultus |  Mennesket bød han at rejse sit åsyn ... og se mod stjernernes vrimmel "
note = "Ovids _Metamorfoser_ 1.85-86, Otto Steen Dues oversættelse (2005)." 

[n23]
lemma = "Quamuis mortalis ... perfruor Ambrosiâ | Dødelig er jeg nok ... mit hoved til himlen"
note = "Dette epigram er (Tychos?) oversættelse af et antikt epigram fra den græske antologi, som i følge overleveringen er skrevet af Ptolemaios (Anth. Palat. 9.577). Samme epigram, men i anden version, har Tycho anvendt i en stambog (TBOO IX, 215.8-15). De sidste to vers genfindes ordret som v. 53-54 i den elegi til Urania der optræder som efterskrift i bogen om den nye stjerne (1573). Ligeledes har epigrammets v. 5-6 en vis lighed med elegiens følgende distikon (55-56). Epigrammet er oversat af Peter Zeeberg." 

[n24]
lemma = "Eobanus | Eobanus"
note = "Helius Eobanus Hessus (1488-1540), tysk humanist og latindigter. Citatet, formentlig et epigram, har ikke kunnet identificeres blandt hans værker." 

[n25]
lemma = "O quam mira ...nil gigneret æquor | Oh, hvor er dog himmelens kraft ... intet frembringe"
note = "Citat fra det latinske læredigt _Zodiacus vitae_ (bog 10, v. 70-71) af Marcellus Palingenius Stellatus, pseudonym for den italienske digter Pier Angelo Manzolli (ca. 1500-før 1551). Digtet udkom første gang i Venedig formentlig i 1534. Det første vers (_O quam mira et magna potentia cœli est_) er dog forkert citeret – og derfor også metrisk forkert. Det korrekte citat er: _O quam mira, et quam miranda potentia caeli est_." 

[n26]
lemma = "Derfor siger Moses | Quapropter Moses"
note = "1. Mos. 1.14." 

[n28]
lemma = "teste Plinio | if. Plinius"
note = "Plinius d.æ. (23-79): _Naturalis historia_ 2.95." 

[n31]
lemma = "aphæticam | aphetisk"
note = "Apheten (lat. _apheta_, fra gr. _aphetes_) er det element i horoskopet der er udpeget til at bestemme livslængden. Kaldes også _hyleg_." 

[n32]
lemma = "anaretæ | anaretens"
note = "_Anareta_ (gr. _anairetes_) (livs)ødelæggeren, en fjendtlig planet der står i et dårligt aspekt til den livgivende planet (apheten)." 

[n33]
lemma = "locum Lunæ ... tempore conceptionis faciant in partu ascendentem | gøre Månens sted på undfangelsestidspunktet til ascendanten"
note = "Her er tale om den såkaldte _trutina Hermetis_ (Hermes’ vægt), en teori ifølge hvilken månens position ved undfangelsen er identisk med ascendantens position ved fødslen. Teorien kendes fra _Centiloquium_ ‘De hundrede sentenser’ er den latinske titel på en samling græske astrologiske teser (på græsk _Karpos_ ’Frugten’), som med urette er tilskrevet Ptolemæus og som i det 15. og 16. årh. blev meget læst i latinske oversættelse." 

[n34]
lemma = "inferioris naturæ | den lavere natur"
note = "Dvs. i kroppen." 

[n35]
lemma = "occulta | skjulte"
note = "Tycho bruger ofte ordet _occultus_, skjult, om astrologien." 

[n36]
lemma = "Esau et Jacob | Esau og Jakob"
note = "Malachias 1.2-3; Romerbrevet 9.13."   

[n37]
lemma = "de prohibitis in lege Mosaica prædictionibus Astrologicis | forbud mod astrologiske forudsigelser i Moseloven"
note = "5\\. Mosebog 18.10 ff." 

[n38]
lemma = "Jeremiæ dictum | Jeremias' udsagn"
note = "Jeremias 10.2" 

[n39]
lemma = "non esse timendos eos, qui corpus occidere possunt, in animam uero nullam habent potestatem | at man ikke skal frygte dem, der kan dræbe ens krop, men ingen magt har over ens sjæl"
note = "Matthæus 10.28." 

[n40]
lemma = "Stent et saluent te augures cœli, qui contemplabantursidera, et supputabant menses, ut ex ijs annuncient ventura tibi |  Lad himmeltyderne træde frem og frelse dig, de som så på stjerner og beregnede månederne for ud fra dem at kunne fortælle dig om det, der vil komme"
note = "Esajas 47.10." 

[n41]
lemma = "Sic reprehenditur in sacris literis Rex Asa | således kritiseres kong Asa i den hellige skrift"
note = "2\\. Krøn. 16.12" 

[n42]
lemma = "verum et supramundanum hominem | det sande og overjordiske menneske"
note = "Dvs. Kristus." 

[n43]
lemma = "Centiloquij | Centiloquium"
note = "_Centiloquium_ ‘De hundrede sentenser’ er den latinske titel på en samling græske astrologiske teser (på græsk _Karpos_, ’Frugten’), som med urette er tilskrevet Ptolemæus og som i det 15. og 16. årh. blev meget læst i latinske oversættelse." 

[n44]
lemma = "Nescia mens hominum fati ... rebus elata secundis | Blindt er menneskesindet ... at holde sig inden for grænser"
note = "Vergil _Æneiden_ 10.501-502; Otto Steen Dues oversættelse. I den latinske original står der fejlagtigt _elata_ i stedet for _sublata_, hvilket forstyrrer metrikken" 

[n45]
lemma = "De maleficis et Mathematicis | »Om troldmænd og matematikere«"
note = "_Codex Justiniani_ 9.18." 

[n47]
lemma = "Accursius"
note = "Italiensk jurist (1182-1263?), professor i Bologna, forfatter til _Glossa ordinaria_, en kommentar til Justinian." 

[n48]
lemma = "Scire docet Mathesis sed diuinare Mathesis"
note = "Som Tycho rigtigt harcelerer over i det følgende, er dette heksameter metrisk elendigt og indholdsmæssigt meningsløst. Oversat betyder det: ‘Mathesis (viden) underviser i at vide, men mathesis (astrologi) underviser i at gætte/spå’. Se Tychos nådesløse dom nedenfor." 

[n49]
lemma = "sillaba pariter longam et breuem | såvel kort som lang anden stavelse"
note = "Det græske ord _mathêsis_ staves med êta kan kun skanderes kort-lang-kort, men Accursius kender ikke forskel på êta og epsilon." 

[n50]
lemma = "L. 2. C. de Malef. et Mathematicis | (L. 2. C Om troldmænd og matematikere)"
note = "Tychos reference." 

[n51]
lemma = "Scilicet arma magis ... vincere major erat. |  Mægtige Stifter af Rom! ... Stjernerne kendte du slet"
note = "Ovid _Fasti_ 1.29-30, Høegs og Rubows oversættelse." 

[n52]
lemma = "ejecerunt | de"
note = "‘De’ må være juristerne." 

[n53]
lemma = "Hyppocrates | Hippokrates"
note = "Hippokrates fra Kos (ca. 460 - ca. 370 f.Kr.), græsk læge, der traditionelt opfattes som lægekunstens fader. Han selv og især hans elever har efterladt sig et større korpus af lægevidenskabeige værker." 

[n54]
lemma = "Erastus"
note = "Th. Erastus (1524-1583): _Defensio libelli Hieronymi Savonarolæ de astrologia diviaitrice_ (Paris 1569, s. 123)." 

[n55]
lemma = "[beskæftiger sig med]"
note = "Teksten synes her at mangle et par ord."

[n56]
lemma = "Etymologiæ nominis sui congruus | i overensstemmelse med sit navns etymologi"
note = "Tycho tænker her enten på det latinske ord _errare_, der betyder ‘tage fejl’, ‘være på vildspor’, eller på at Erastus på græsk betyder ‘elsket’; Tycho vrider muligvis ordet til at betyde ‘elsker’ – og derved både viljesløs slave og grum forfører, se nedenfor." 

[n57]
lemma = "Paracelsi | Paracelsus’"
note = "Paracelsus (Theophrastus Bombastus von Hohenheim, 1493-1541), schweizisk læge, der gjorde op med lægekunstens hidtidige dogmer til fordel for egne teorier i et kompliceret system, der bl.a. inddrog kemi og astrologi. Tycho Brahes kemiske og medicinske tanker var stærkt påvirket af Paracelsus." 

[n58]
lemma = "de mineralium et herbarum e terrâ evulsionibus |  opgravningen af mineraler og urter"
note = "Her tænkes formentlig på den astrologisk bestemte tidspunkter og ritualer i forbindelse med, at mineraler og lægeplanter blev gravet op af jorden, og ved fremstillingen af medikamenter." 

[n59]
lemma = "_Nec sutor ultra crepidam_ |  ‘Skomager, bliv ved din læst’"
note = "Ordsprogets latinske form findes allerede hos Plinius d.æ. (_Naturalis Historia_ 35.80)" 

[n60]
lemma = "_Ardeam auem ob id vocis strepitu aquas culpare aiunt, quia nare non didicerit_ | ‘Man siger, at hejren skælder ud på vandet med sin knebren, fordi den ikke har lært at svømme.’"
note = "Mau, _Dansk Ordsprogs-Skat_ 3534." 

[n61]
lemma = "Picus Comes Mirandulæ | Pico greve af Mirandola"
note = "Giovanni Pico della Mirandola (1463-1494) italiensk greve og filosof, hvis posthumt udgivne værk Om menneskets værdighed for eftertiden står som et af renæssancehumanismens manifester. Tycho henviser til et andet værk _Disputationes in astrologiam divinatricem_ (Diskussioner om astrologi, 1496), og måske til hans ufuldendte værk _Contra hostes ecclesiæ_ (mod kirkens fjender)." 

[n62]
lemma = "Apotelesmata | apotelesmata"
note = "_Apotelesma_ (græsk, plur.: _apotelesmata_) betyder ‘indflydelse’, ‘påvirkning’. Ordet dukker op i senantikke latinske tekster." 

[n63]
lemma = "Lucius Belantius"
note = "it. Lucio Bellanzio, _De astrologica veritate quæstiones, et astrologiæ defensio contra Picum_ (Spørgsmål om astrologiens sandhed og forsvar for astrologien mod Pico, Basel 1554)." 

[n64]
lemma = "Lucas Gauricus"
note = "it. Luca Gaurico (1475-1558), italiensk astrolog, astronom. Han blev biskop, først i sin fødeby Giffoni, senere i Civitate. Tycho refererer til hans værk _Tractatus astrologicus_ (Venedig 1552) fol 58r. " 

[n68]
lemma = "HÆC POST ORATIONEM SUBIUNGENDA | Dette bør tilføjes efter talen"
note = "Denne tilføjelse findes kun i manuskriptet, hvis sidste del er delvis ulæseligt." 

[n69]
lemma = "Nicolaum Hemmingium | Niels Hemmingsen"
note = "Niels Hemmingsen (1513-1600), professor i teologi i København 1579, senere afsat for sine calvinske synspunkter og udpeget til kannik i Roskilde. 1572 udgav han _Commentaria in omnes epistolas apostolorum_, hvori han under gennemgangen af Efeserbrevet 6.1-3 (s. 441f) bruger Calvins værk _Admonitio adversus Astrologiam_ (1549) s. 15ff." 

[n72]
lemma = "Albertus Knopperus"
note = "Albert Knopper(t), født i Zwolle, 1546 doktor i Rostock, hvor han læste over romerretten. 1549 professor juris i København, ofte brugt som diplomat for Frederik II i udlandet. Død på en diplomatisk mission efter et røverisk overfald i Löwen 1576."  

[n73]
lemma = "olim Lipsiæ operam dare uestræ Jurisprudentiæ ex parentum uoluntate cogebar | engang blev jeg tvunget til at beskæftige mig med jeres jura i Leipzig efter mine forældres ønske"
note = "Tycho studerede i Leipzig 1562-1565 – jura dog kun noget af tiden." 

[n74]
lemma = "Scire docet Mathesis, dat diuinare Mathesis"
note = "Sammenlign den lidt afvigende formulering ovenfor." 

[n75]
lemma = "Græca sunt, legi non possunt"
note = "‘Det er græsk og kan ikke læses.’" 

[n76]
lemma = "Aristarcho | Aristarch"
note = "Aristarchos fra Samothrake (ca. 220-144 f.Kr.), gr. homerfilolog, bibliotekar i Alexandria. Bruges som indbegrebet af en hård kritiker." 

[n78]
lemma = "Epicureus | Epikur"
note = "Den græske filosof Epikur (ca. 300 f.Kr.) indarbejdede forgængeren Demokrits atomteori i sit filosofiske system, hvori de kun findes ‘fyldt og tomt’ dvs. atomer og tomrum. Guder har ikke plads i dette materialistiske verdensbillede." 

[n79]
lemma = "Peucero | Peucerus"
note = "Caspar Peucer (1525-1602), ty. reformatior og naturvidenskabsmand, der bl.a. udgav _Hypoteses astronomicæ seu theoriæ planetarum ex Ptolemæi et aliorum veterum doctrina ad observationes Nicolai Copernici et canones ab eo conditos accomodatæ_ (Wittenberg 1571)." 

[n80]
lemma = "Dasipodio | Dasipodius"
note = "Conrad Dasypodius (1530/1532-1600/1601), schweizisk astronom, der bl.a. udgav _Hyposetes orbium cœlestium congruente cum tabulis Alphonsi et Coperniciseu etiam tabulis Prutenicis_ (Strassburg 1568)."
